version: '3.1'

services:
  itsmycolor_db:
    image: mysql:latest
    container_name: itsmycolor_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gulmat456
      MYSQL_DATABASE: itsmycolor
    ports:
      - '3306:3306'
    volumes:
      - ./dumps/test:/docker-entrypoint-initdb.d
    platform: linux/x86_64
